/* The following code was generated by JFlex 1.3.5 on 02-12-16 22:00 */

/* ------------------------Codigo copiado al inicio de la clase---------------------- */
/* Esta seccion contiene codigo que se copiara literalmente al principio de la clase, aqui
se define el paquete y los import necesarios. */


// imports para la clase
import java_cup.runtime.ComplexSymbolFactory;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 02-12-16 22:00 from the specification file
 * <tt>file:/C:/Users/Florencia/workspace/Tarea2Teoria/lexer.jflex</tt>
 */
public class Lexer implements sym, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static String yycmap_packed = 
    "\11\0\1\6\1\5\1\0\1\6\1\4\22\0\1\6\14\0\1\13"+
    "\2\0\12\3\1\0\1\35\5\0\2\2\2\0\1\1\10\0\1\2"+
    "\1\1\2\0\1\2\2\1\1\0\1\2\12\0\1\10\1\7\1\24"+
    "\1\26\1\20\1\31\1\0\1\33\1\27\1\11\1\0\1\15\1\17"+
    "\1\22\1\25\1\14\1\0\1\12\1\34\1\23\1\16\1\21\1\32"+
    "\2\0\1\30\1\36\1\0\1\37\uff82\0";

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = yy_unpack_cmap(yycmap_packed);

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    32,    32,    32,    64,    96,    32,   128,   160,   192, 
      224,   256,   288,   320,   352,   384,   416,   448,   480,    32, 
       32,    32,   512,   544,   576,   608,   640,   672,   704,   736, 
      768,   800,   832,    32,    32,   864,    32,   896,   928,   960, 
      992,    32,  1024,  1056,  1088,    32,  1120,  1152,  1184,  1216, 
     1248,  1280,  1312,  1344,  1376,  1408,    32,  1440,    32,  1472, 
     1504,  1536,  1568,    32,  1600,  1632,  1664,  1696,  1728,  1760, 
       32,  1792,  1824,  1856,  1888,  1920,  1952,  1984,  2016,    32, 
     2048,  2080,  2112,  2144,  2176,  2208,  2240,  2272,  2304,  2336, 
     2368,  2400,  2432,  2464,  2496,  2528,  2560,  2592,  2624,    32, 
       32,  2656,  2688,  2720,  2752,  2784,  2816,  2848,  2880,  2912, 
     2944,  2976,    32,    32,  3008,  3040,    32,    32,  3072,    32, 
     3104,  3136,  3168,  3200,    32,  3232,    32
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\6\2\7\1\10\1\11"+
    "\3\2\1\12\1\13\2\2\1\14\1\2\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\2\2\1\23\2\2\1\24"+
    "\1\25\1\26\43\0\1\5\41\0\1\7\42\0\1\27"+
    "\14\0\1\30\33\0\1\31\1\32\32\0\1\33\42\0"+
    "\1\34\34\0\1\35\47\0\1\36\22\0\1\37\22\0"+
    "\1\40\31\0\1\41\24\0\1\42\52\0\1\43\1\0"+
    "\1\44\41\0\1\45\41\0\1\46\15\0\1\47\40\0"+
    "\1\50\35\0\1\51\55\0\1\52\27\0\1\53\42\0"+
    "\1\54\52\0\1\55\26\0\1\56\23\0\1\57\50\0"+
    "\1\60\34\0\1\61\34\0\1\62\54\0\1\63\20\0"+
    "\1\64\55\0\1\65\33\0\1\66\34\0\1\67\30\0"+
    "\1\70\47\0\1\71\34\0\1\72\44\0\1\73\42\0"+
    "\1\74\32\0\1\75\34\0\1\76\34\0\1\77\45\0"+
    "\1\100\47\0\1\101\17\0\1\102\51\0\1\103\35\0"+
    "\1\104\31\0\1\105\51\0\1\106\33\0\1\107\32\0"+
    "\1\110\34\0\1\111\42\0\1\112\47\0\1\113\26\0"+
    "\1\114\40\0\1\115\50\0\1\116\27\0\1\117\35\0"+
    "\1\120\35\0\1\121\13\0\1\122\1\0\1\123\21\0"+
    "\1\124\54\0\1\125\26\0\1\126\52\0\1\127\25\0"+
    "\1\130\31\0\1\131\2\0\1\132\52\0\1\133\41\0"+
    "\1\134\22\0\1\135\40\0\1\136\41\0\1\137\47\0"+
    "\1\140\30\0\1\141\31\0\1\142\41\0\1\143\42\0"+
    "\1\144\34\0\1\145\40\0\1\146\50\0\1\147\31\0"+
    "\1\150\43\0\1\151\34\0\1\152\31\0\1\153\55\0"+
    "\1\154\24\0\1\155\50\0\1\156\31\0\1\157\33\0"+
    "\1\160\34\0\1\161\54\0\1\162\21\0\1\163\45\0"+
    "\1\164\37\0\1\165\32\0\1\166\43\0\1\167\33\0"+
    "\1\170\45\0\1\171\36\0\1\172\41\0\1\173\36\0"+
    "\1\174\31\0\1\175\46\0\1\176\30\0\1\177\27\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  9,  9,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  9,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  9,  9,  0,  9,  0,  0,  0,  0,  9,  0,  0,  0,  9,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  9,  0,  0,  0,  0,  9, 
     0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  9, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  9,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     9,  9,  0,  0,  9,  9,  0,  9,  0,  0,  0,  0,  9,  0,  9
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
	// variable e inicializadores para trabajar con cup.
    private ComplexSymbolFactory symbolFactory;
    
	public Lexer(ComplexSymbolFactory sf, java.io.InputStream is){
		this(is);
        symbolFactory = sf;
    }
	public Lexer(ComplexSymbolFactory sf, java.io.Reader reader){
		this(reader);
        symbolFactory = sf;
    }
    
    
	// funciones para generar simbolos (con y sin valor asociado).
    public Symbol symbol(String name, int code){
		return symbolFactory.newSymbol(name, code,
						new Location(yyline+1,yycolumn+1, yychar),
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength())
				);
    }
    public Symbol symbol(String name, int code, Object value){
		return symbolFactory.newSymbol(name, code, 
						new Location(yyline+1, yycolumn +1, yychar), 
						new Location(yyline+1,yycolumn+yylength(), yychar+yylength()), 
						value);
    }
    
    
    // funcion para enviar errores.
    private void send_error(String error) {
    	throw new Error("at line: " + (yyline+1) + " column: " + yycolumn + ". " + error);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3264];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] yy_unpack_cmap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 112) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 63: 
          { return symbolFactory.newSymbol("borde",BORDE);  }
        case 128: break;
        case 126: 
          { return symbolFactory.newSymbol("direccion_pluma",DIRP);  }
        case 129: break;
        case 119: 
          { return symbolFactory.newSymbol("pluma_arriba",PARRIBA);  }
        case 130: break;
        case 116: 
          { return symbolFactory.newSymbol("color_tablero",TCOLOR);  }
        case 131: break;
        case 3: 
          { return symbolFactory.newSymbol("color",COLOR,yytext());  }
        case 132: break;
        case 21: 
          { return symbolFactory.newSymbol("}",CIERRA,yytext()); }
        case 133: break;
        case 19: 
          { return symbolFactory.newSymbol(";",PTOCOMA,yytext()); }
        case 134: break;
        case 56: 
          { return symbolFactory.newSymbol("else",ELSE,yytext()); }
        case 135: break;
        case 58: 
          { return symbolFactory.newSymbol("then",THEN,yytext()); }
        case 136: break;
        case 100: 
          { return symbolFactory.newSymbol("direccion_actual",DIRACT);  }
        case 137: break;
        case 2: 
          { return symbolFactory.newSymbol("direccion",DIRECCION,yytext());  }
        case 138: break;
        case 117: 
          { return symbolFactory.newSymbol("color_pluma",COLORP);  }
        case 139: break;
        case 113: 
          { return symbolFactory.newSymbol("pluma_abajo",PABAJO);  }
        case 140: break;
        case 112: 
          { return symbolFactory.newSymbol("bajar_pluma",BAJARP);  }
        case 141: break;
        case 99: 
          { return symbolFactory.newSymbol("color_pluma",PCOLOR);  }
        case 142: break;
        case 79: 
          { return symbolFactory.newSymbol("avanza_pluma",AVANZA);  }
        case 143: break;
        case 70: 
          { return symbolFactory.newSymbol("while",WHILE,yytext()); }
        case 144: break;
        case 5: 
        case 6: 
          { ; /* Ignora*/ }
        case 145: break;
        case 1: 
        case 7: 
        case 8: 
        case 9: 
        case 10: 
        case 11: 
        case 12: 
        case 13: 
        case 14: 
        case 15: 
        case 16: 
        case 17: 
        case 18: 
          { send_error("error"); }
        case 146: break;
        case 124: 
          { return symbolFactory.newSymbol("levantar_pluma",LEVANTARP);  }
        case 147: break;
        case 33: 
          { return symbolFactory.newSymbol("or",OR,yytext()); }
        case 148: break;
        case 34: 
          { return symbolFactory.newSymbol("do",DO,yytext()); }
        case 149: break;
        case 36: 
          { return symbolFactory.newSymbol("if",IF,yytext()); }
        case 150: break;
        case 4: 
          { return symbolFactory.newSymbol("number",NUMBER,Integer.parseInt(yytext()));  }
        case 151: break;
        case 20: 
          { return symbolFactory.newSymbol("{",ABRE,yytext()); }
        case 152: break;
        case 41: 
          { return symbolFactory.newSymbol("and",AND,yytext()); }
        case 153: break;
        case 45: 
          { return symbolFactory.newSymbol("not",NOT,yytext()); }
        case 154: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              {     return symbol("EOF", EOF); 
 }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
