
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.Scanner;
import java_cup.runtime.ComplexSymbolFactory.Location;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\024\000\002\002\004\000\002\004\003\000\002\002" +
    "\003\000\002\002\003\000\002\002\004\000\002\002\004" +
    "\000\002\002\004\000\002\002\010\000\002\002\014\000" +
    "\002\002\010\000\002\002\005\000\002\003\004\000\002" +
    "\003\003\000\002\003\004\000\002\003\004\000\002\003" +
    "\003\000\002\003\003\000\002\003\005\000\002\003\005" +
    "\000\002\003\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\055\000\020\004\010\005\011\006\014\007\006\010" +
    "\007\021\012\022\005\001\002\000\006\002\000\032\041" +
    "\001\002\000\020\011\025\012\024\013\017\014\026\015" +
    "\023\027\022\034\020\001\002\000\004\020\052\001\002" +
    "\000\004\016\051\001\002\000\010\002\uffff\031\uffff\032" +
    "\uffff\001\002\000\010\002\ufffe\031\ufffe\032\ufffe\001\002" +
    "\000\020\011\025\012\024\013\017\014\026\015\023\027" +
    "\022\034\020\001\002\000\004\002\016\001\002\000\004" +
    "\017\015\001\002\000\010\002\ufffd\031\ufffd\032\ufffd\001" +
    "\002\000\004\002\001\001\002\000\004\020\050\001\002" +
    "\000\004\017\047\001\002\000\010\023\035\025\031\026" +
    "\032\001\002\000\020\011\025\012\024\013\017\014\026" +
    "\015\023\027\022\034\020\001\002\000\012\023\ufff2\025" +
    "\ufff2\026\ufff2\033\ufff2\001\002\000\012\023\ufff5\025\ufff5" +
    "\026\ufff5\033\ufff5\001\002\000\004\017\027\001\002\000" +
    "\012\023\ufff1\025\ufff1\026\ufff1\033\ufff1\001\002\000\012" +
    "\023\ufff6\025\ufff6\026\ufff6\033\ufff6\001\002\000\012\023" +
    "\uffee\025\031\026\032\033\uffee\001\002\000\020\011\025" +
    "\012\024\013\017\014\026\015\023\027\022\034\020\001" +
    "\002\000\020\011\025\012\024\013\017\014\026\015\023" +
    "\027\022\034\020\001\002\000\012\023\uffef\025\uffef\026" +
    "\uffef\033\uffef\001\002\000\012\023\ufff0\025\ufff0\026\ufff0" +
    "\033\ufff0\001\002\000\004\030\036\001\002\000\020\004" +
    "\010\005\011\006\014\007\006\010\007\021\012\022\005" +
    "\001\002\000\006\031\040\032\041\001\002\000\012\002" +
    "\ufffa\024\043\031\ufffa\032\ufffa\001\002\000\020\004\010" +
    "\005\011\006\014\007\006\010\007\021\012\022\005\001" +
    "\002\000\010\002\ufff7\031\ufff7\032\ufff7\001\002\000\004" +
    "\030\044\001\002\000\020\004\010\005\011\006\014\007" +
    "\006\010\007\021\012\022\005\001\002\000\006\031\046" +
    "\032\041\001\002\000\010\002\ufff9\031\ufff9\032\ufff9\001" +
    "\002\000\012\023\ufff3\025\ufff3\026\ufff3\033\ufff3\001\002" +
    "\000\012\023\ufff4\025\ufff4\026\ufff4\033\ufff4\001\002\000" +
    "\010\002\ufffb\031\ufffb\032\ufffb\001\002\000\010\002\ufffc" +
    "\031\ufffc\032\ufffc\001\002\000\010\025\031\026\032\033" +
    "\054\001\002\000\004\030\055\001\002\000\020\004\010" +
    "\005\011\006\014\007\006\010\007\021\012\022\005\001" +
    "\002\000\006\031\057\032\041\001\002\000\010\002\ufff8" +
    "\031\ufff8\032\ufff8\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\055\000\006\002\003\004\012\001\001\000\002\001" +
    "\001\000\004\003\052\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\003" +
    "\020\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\003\027\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\003\033" +
    "\001\001\000\004\003\032\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\002\036\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\002\041\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\002\044" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\002\055\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** User initialization code. */
  public void user_init() throws java.lang.Exception
    {
//@@CUPDBG1

  ComplexSymbolFactory f = new ComplexSymbolFactory();
  symbolFactory = f;
  Scanner scanner = new Scanner(System.in);
  print("nombre del archivo:");
  String archivo = scanner.nextLine();
  File file = new File(archivo);
  FileInputStream fis = null;
  try {
    fis = new FileInputStream(file);
  } catch (IOException e) {
    e.printStackTrace();
  } 
  lexer = new Lexer(f,fis);
  scanner.close();

    }

  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
//@@CUPDBG2
 return lexer.next_token(); 
    }

//@@CUPDBG0

  protected Lexer lexer;


  public void print(String s){
	System.out.println(s);
  }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= ROOT EOF 
            {
              Object RESULT =null;
		Location start_valxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xleft;
		Location start_valxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).xright;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // ROOT ::= OP 
            {
              Object RESULT =null;
		//@@CUPDBG3
 print("root"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("ROOT",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // OP ::= BAJARP 
            {
              Object RESULT =null;
		//@@CUPDBG4
 print("bajap") ;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // OP ::= LEVANTARP 
            {
              Object RESULT =null;
		//@@CUPDBG5
 print("subep"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // OP ::= COLORP COLOR 
            {
              Object RESULT =null;
		//@@CUPDBG6
 print("setear color"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // OP ::= DIRP DIRECCION 
            {
              Object RESULT =null;
		//@@CUPDBG7
 print("set direcicon"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // OP ::= AVANZA NUMBER 
            {
              Object RESULT =null;
		Location nxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xleft;
		Location nxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xright;
		Object n = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		//@@CUPDBG8
 print("avanza"+n); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // OP ::= IF EXPR THEN ABRE OP CIERRA 
            {
              Object RESULT =null;
		//@@CUPDBG9
 print("if"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // OP ::= IF EXPR THEN ABRE OP CIERRA ELSE ABRE OP CIERRA 
            {
              Object RESULT =null;
		//@@CUPDBG10
 print("if else"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // OP ::= WHILE EXPR DO ABRE OP CIERRA 
            {
              Object RESULT =null;
		//@@CUPDBG11
 print("while"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // OP ::= OP PTOCOMA OP 
            {
              Object RESULT =null;
		//@@CUPDBG12
 print("op ; op"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("OP",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // EXPR ::= TCOLOR COLOR 
            {
              Object RESULT =null;
		//@@CUPDBG13
 print("color de tabla"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // EXPR ::= BORDE 
            {
              Object RESULT =null;
		//@@CUPDBG14
 print("borde"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // EXPR ::= DIRACT DIRECCION 
            {
              Object RESULT =null;
		//@@CUPDBG15
 print("direccion actual"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // EXPR ::= PCOLOR COLOR 
            {
              Object RESULT =null;
		Location colxleft = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xleft;
		Location colxright = ((java_cup.runtime.ComplexSymbolFactory.ComplexSymbol)CUP$Parser$stack.peek()).xright;
		Object col = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		//@@CUPDBG16
 print("es color" +col); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // EXPR ::= PARRIBA 
            {
              Object RESULT =null;
		//@@CUPDBG17
 print("subir"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // EXPR ::= PABAJO 
            {
              Object RESULT =null;
		//@@CUPDBG18
 print("bajar") ;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // EXPR ::= EXPR AND EXPR 
            {
              Object RESULT =null;
		//@@CUPDBG19
 print("exp y exp"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // EXPR ::= EXPR OR EXPR 
            {
              Object RESULT =null;
		//@@CUPDBG20
 print("exp o exp"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // EXPR ::= NOT EXPR 
            {
              Object RESULT =null;
		//@@CUPDBG21
 print("no exp"); 
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("EXPR",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
