
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LEVANTARP = 3;
  public static final int AND = 19;
  public static final int PABAJO = 10;
  public static final int ELSE = 18;
  public static final int DIRECCION = 14;
  public static final int OR = 20;
  public static final int THEN = 17;
  public static final int WHILE = 16;
  public static final int NOT = 21;
  public static final int COLOR = 13;
  public static final int IF = 15;
  public static final int AVANZA = 6;
  public static final int DO = 25;
  public static final int TCOLOR = 7;
  public static final int COLORP = 4;
  public static final int BORDE = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 12;
  public static final int ABRE = 22;
  public static final int error = 1;
  public static final int BAJARP = 2;
  public static final int DIRP = 5;
  public static final int PTOCOMA = 24;
  public static final int CIERRA = 23;
  public static final int PARRIBA = 11;
  public static final int DIRACT = 9;
  public static final int PCOLOR = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BAJARP",
  "LEVANTARP",
  "COLORP",
  "DIRP",
  "AVANZA",
  "TCOLOR",
  "BORDE",
  "DIRACT",
  "PABAJO",
  "PARRIBA",
  "NUMBER",
  "COLOR",
  "DIRECCION",
  "IF",
  "WHILE",
  "THEN",
  "ELSE",
  "AND",
  "OR",
  "NOT",
  "ABRE",
  "CIERRA",
  "PTOCOMA",
  "DO",
  "PCOLOR"
  };
}

